-- ClauDinhos Chat
-- Bootstrap de schema para PostgreSQL 17+
-- Execute este arquivo dentro do banco de dados de destino.

BEGIN;

CREATE TABLE IF NOT EXISTS django_migrations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS django_content_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label varchar(100) NOT NULL,
    model varchar(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_key UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS django_session_expire_date_idx
    ON django_session (expire_date);

CREATE TABLE IF NOT EXISTS chat_conversation (
    id uuid PRIMARY KEY,
    title varchar(160) NOT NULL,
    model_name varchar(120) NOT NULL,
    system_prompt text NOT NULL DEFAULT 'Voce e uma inteligencia artificial para responder questionamentos em geral. Voce tem um grande senso de humor e gosta de fazer analogias usando seus colegas como exemplo. Os principais nomes sao Erick, Gui, Vini e Leo. Sempre que possivel, crie parodias sobre o Erick e use jargoes com ditados populares.',
    context_limit_tokens integer NOT NULL DEFAULT 16384,
    available_models_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
    is_archived boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_conversation_context_limit_tokens_check CHECK (context_limit_tokens >= 0)
);

CREATE INDEX IF NOT EXISTS chat_conversation_updated_at_idx
    ON chat_conversation (updated_at DESC);

CREATE INDEX IF NOT EXISTS chat_conversation_created_at_idx
    ON chat_conversation (created_at DESC);

CREATE TABLE IF NOT EXISTS chat_message (
    id uuid PRIMARY KEY,
    conversation_id uuid NOT NULL,
    role varchar(20) NOT NULL,
    content text NOT NULL,
    sequence_number integer NOT NULL,
    input_tokens_estimated integer NULL,
    output_tokens_estimated integer NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chat_message_conversation_id_fk
        FOREIGN KEY (conversation_id)
        REFERENCES chat_conversation (id)
        ON DELETE CASCADE,
    CONSTRAINT unique_message_sequence_per_conversation
        UNIQUE (conversation_id, sequence_number),
    CONSTRAINT chat_message_role_check
        CHECK (role IN ('system', 'user', 'assistant')),
    CONSTRAINT chat_message_sequence_number_check
        CHECK (sequence_number >= 0),
    CONSTRAINT chat_message_input_tokens_estimated_check
        CHECK (input_tokens_estimated IS NULL OR input_tokens_estimated >= 0),
    CONSTRAINT chat_message_output_tokens_estimated_check
        CHECK (output_tokens_estimated IS NULL OR output_tokens_estimated >= 0)
);

CREATE INDEX IF NOT EXISTS chat_message_conversation_id_idx
    ON chat_message (conversation_id);

CREATE INDEX IF NOT EXISTS chat_message_created_at_idx
    ON chat_message (created_at DESC);

INSERT INTO django_migrations (app, name, applied)
VALUES
    ('contenttypes', '0001_initial', CURRENT_TIMESTAMP),
    ('contenttypes', '0002_remove_content_type_name', CURRENT_TIMESTAMP),
    ('sessions', '0001_initial', CURRENT_TIMESTAMP),
    ('chat', '0001_initial', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

COMMIT;