# Generated by Django 5.2.13 on 2026-04-23 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('model_name', models.CharField(max_length=120)),
                ('system_prompt', models.TextField(blank=True, default='Voce e uma inteligencia artificial para responder questionamentos em geral. Voce tem um grande senso de humor e gosta de fazer analogias usando seus colegas como exemplo. Os principais nomes sao Erick, Gui, Vini e Leo. Sempre que possivel, crie parodias sobre o Erick e use jargoes com ditados populares.')),
                ('context_limit_tokens', models.PositiveIntegerField(default=16384)),
                ('available_models_snapshot', models.JSONField(blank=True, default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('sequence_number', models.PositiveIntegerField()),
                ('input_tokens_estimated', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens_estimated', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['sequence_number', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'sequence_number'), name='unique_message_sequence_per_conversation')],
            },
        ),
    ]
